# Generated by Django 3.2.16 on 2022-12-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('account_book_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('written', models.DateField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('short_url_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('encoded', models.CharField(max_length=1000)),
                ('expired', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_books.accountbook')),
            ],
        ),
    ]
