# Generated by Django 3.2.16 on 2022-12-21 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('account_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('written', models.DateField()),
            ],
            options={
                'db_table': 'ACCOUNT_BOOK',
            },
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('short_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('encoded', models.CharField(max_length=1000)),
                ('expired', models.DateTimeField()),
            ],
            options={
                'db_table': 'SHORT_URL',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_books.accountbook')),
            ],
            options={
                'db_table': 'DETAIL',
            },
        ),
    ]
