# Generated by Django 3.2.16 on 2022-12-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountbook',
            table='ACCOUNT_BOOK',
        ),
        migrations.AlterModelTable(
            name='detail',
            table='DETAIL',
        ),
        migrations.AlterModelTable(
            name='shorturl',
            table='SHORT_URL',
        ),
    ]
