# Generated by Django 3.2.16 on 2022-12-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0002_auto_20221220_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='account_book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
