# Generated by Django 3.2.16 on 2022-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0002_accountbook_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='written',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
