# Generated by Django 3.2.16 on 2022-12-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0003_auto_20221221_0807'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountbook',
            table='ACCOUNT_BOOKS',
        ),
        migrations.AlterModelTable(
            name='shorturl',
            table='SHORT_URLS',
        ),
    ]
