# Generated by Django 3.2.16 on 2022-12-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MEMBERS',
            },
        ),
    ]
